# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy source
COPY package.json tsconfig.json ./
COPY src ./src
COPY bin ./bin
# Install deps and build
RUN npm install && npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY bin ./bin
CMD ["node", "dist/index.js"]
